import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.util.List;

public class Main {
    public static void main(String[] args) {
        try {
            System.setOut(new java.io.PrintStream(System.out, true, StandardCharsets.UTF_8));
            System.setErr(new java.io.PrintStream(System.err, true, StandardCharsets.UTF_8));

            // ── 1. Read source file ───────────────────────────────────────────
            String inputFile = (args.length > 0) ? args[0] : "input.bn";
            String code = Files.readString(Path.of(inputFile), StandardCharsets.UTF_8);

            
            System.out.println("\n📄 Source file: " + inputFile);
            System.out.println("─".repeat(40));
            System.out.println(code);
            System.out.println("─".repeat(40));

            // ── 2. Lexing ─────────────────────────────────────────────────────
            System.out.println("\n🔍 [Phase 1] Lexing...");
            Lexer lexer = new Lexer(code);

            // ── 3. Parsing ────────────────────────────────────────────────────
            System.out.println("🌳 [Phase 2] Parsing...");
            Parser parser = new Parser(lexer);
            ASTNode root = parser.parse();

            List<String> parseErrors = parser.getErrors();
            if (!parseErrors.isEmpty()) {
                System.out.println("\n⚠️  Parse errors found (" + parseErrors.size() + "):");
                parseErrors.forEach(e -> System.out.println("   • " + e));
            }

            // ── 4. Semantic analysis / type checking ──────────────────────────
            System.out.println("🔎 [Phase 3] Semantic Analysis & Type Checking...");
            SymbolTable st = new SymbolTable();
            try {
                root.checkType(st);
                System.out.println("   ✅ Type checking passed.");
            } catch (RuntimeException e) {
                System.out.println("   ❌ Semantic error: " + e.getMessage());
                // Continue to show symbol table and partial output if possible
            }
            st.display();

            // ── 5. Code generation ────────────────────────────────────────────
            System.out.println("\n⚙️  [Phase 4] Generating Python code...");
            String pythonHeader = "# Generated by বাংলা কম্পাইলার v3.0\n"
                                + "# Source: " + inputFile + "\n\n";
            String pythonBody   = root.generatePython(0);
            String pythonCode   = pythonHeader + pythonBody;

            // ── 6. Write output ───────────────────────────────────────────────
            String outputFile = inputFile.replace(".bn", ".py");
            if (outputFile.equals(inputFile)) outputFile = inputFile + ".py";

            Files.writeString(Path.of(outputFile), pythonCode, StandardCharsets.UTF_8);

            System.out.println("\n📦 Generated Python file: " + outputFile);
            System.out.println("─".repeat(40));
            System.out.println(pythonCode);
            System.out.println("─".repeat(40));

            if (parseErrors.isEmpty()) {
                System.out.println("\n✅ Compilation successful! Run with:  python3 " + outputFile);
            } else {
                System.out.println("\n⚠️  Compiled with " + parseErrors.size() + " error(s). Output may be partial.");
            }

        } catch (Exception e) {
            System.err.println("\n❌ Fatal Error: " + e.getMessage());
            e.printStackTrace();
        }
    }
}
